# CPE100/ISY101: Basic Programming for Engineer
# Module3: Python as an Engineering tool

Array คือ อะไร?

คือ ตัวแปร(Variable) ที่นำเอาข้อมูลที่เป็นชนิด หรือประเภทเดียวกันมาเรียงต่อกัน โดยมีลำดับ(index)กำหนดไว้

![](Array.png)

In [1]:
color_1 = 'Red'
color_2 = 'Blue'
color_3 = 'Green'

In [ ]:
color = ['Red', 'Green', 'Blue']

# `Practice:` NumPy 
---

In [ ]:
# Installation for NumPy
#!pip install -q numpy

In [1]:
# Import NumPy Module
import numpy as np

In [2]:
# check NumPy version
print(np.__version__)

1.26.1


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]




---


# Creating Arrays

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [6]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


##0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [7]:
arr = np.array(42)
print(arr)

42


##1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [8]:
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]


##2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.



In [9]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


##3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

What is Tensor ?

=> Tensor is a container which can house data in N dimensions

In [10]:
arr = np.array([ [[1, 2, 3], [4, 5, 6]], 
                [[1, 2, 3], [4, 5, 6]] ,
                [[1, 2, 3], [1, 2, 3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]]


##Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
# ndarray.ndim

In [11]:
a = np.array(42)
print(a.ndim)

b = np.array([1, 2, 3, 4, 5])
print(b.ndim)

c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.ndim)

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d.ndim)


0
1
2
3


In [12]:
d.ndim

3



---


# Array Indexing

## Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [14]:
arr = np.array([1, 2, 3, 4, 4, 5, 7])
print(arr[3])
print(arr[6])

4
7


## Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

arr[ Y , X]

In [15]:
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


## Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

arr[แผ่น, Y, X]

In [16]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
    ])
print(arr[0, 1, 2])

6


In [19]:
arr[0,1,0]

4

In [18]:
arr[0][1][0]

4

Example Explained

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]

and:

[[7, 8, 9], [10, 11, 12]]

Since we selected 0, we are left with the first array:

[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:

[1, 2, 3] and [4, 5, 6]

Since we selected 1, we are left with the second array:

[4, 5, 6]

The third number represents the third dimension, which contains three values:

4, 5, 6

Since we selected 2, we end up with the third value:

6

## Negative Indexing

Use negative indexing to access an array from the end.

-2 -1 | 0 1 2

In [321]:
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
arr_1 = np.array([[1.1, 1.2, 1.3, 1.4, 1.5],
                 [2.1, 2.2, 2.3, 2.4, 2.5]])

In [ ]:
arr_1[0,-1]

In [ ]:
arr_1[1, -2]

In [ ]:
arr_1[-2, 4]



---

# Array Slicing

## Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: **[start:end]**.

We can also define the step, like this: **[start:end:step]**.

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
## arr[start:stop:step]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) # Pass start and end
print(arr[2:])  # Don’t pass end
print(arr[:3])  # Don’t pass start
print(arr[1:5:2]) # Pass start, end and step

## Negative Slicing

Use the minus operator to refer to an index from the end:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

## STEP

Use the step value to determine the step of the slicing:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

## Slicing 2-D Arrays

In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

In [ ]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

In [ ]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])



---

# Data Types

By default Python have these data types:

* strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
* integer - used to represent integer numbers. e.g. -1, -2, -3
* float - used to represent real numbers. e.g. 1.2, 42.42
* boolean - used to represent True or False.
* complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

## Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array:

In [20]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [49]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [50]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [23]:
arr = np.array([1, 2, 3, 4], dtype=int)
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

ndarray.astype(dType)

In [24]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.999])
print(arr)
print(arr.dtype)
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1.1   2.1   3.999]
float64
[1 2 3]
int32


In [25]:
# Change data type from float to integer by using int as parameter value:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [55]:
# Change data type from integer to boolean:
arr = np.array(['abc','','pos'])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

ValueError: invalid literal for int() with base 10: 'abc'

---

## <span style="color:red"> Question: </span> Try to use Python's commands and NumPy's function to create provided output

Q1:Create a new array of 2*2 integers, without initializing entries.   
e.g.   
array([0,0],  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0,0])

In [27]:
arr = np.zeros((2, 2), dtype='i')
print(arr, '\n\n', arr.dtype)

[[0 0]
 [0 0]] 

 int32


Q2:Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [28]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
newarr = X.copy()
print('This is old array\n',X)
print('This is new array\n',newarr)

This is old array
 [[1 2 3]
 [4 5 6]]
This is new array
 [[1 2 3]
 [4 5 6]]


Q3:Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [29]:
arr = np.eye(3,dtype='i')
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [30]:
shape = (3, 3, 3)
arr = np.zeros((3, 3, 3))

for i in range(shape[0]):
  for j in range(shape[0]):
    for k in range(shape[0]):
      if i == j and j == k:
        arr[i][j][k] = 1

# Print the array
print(arr)

[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 1.]]]


Q4:Create a new array of 3*2 float numbers, filled with ones.

In [31]:
arr = np.ones((3, 2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Q5:Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [33]:
x = np.arange(4, dtype="int64")
print(x)

[0 1 2 3]


Q6:Create a new array of 3*2 float numbers, filled with zeros.

Q7:Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

Q8:Create a new array of 2*5 uints, filled with 6.

In [ ]:
print(np.full((2, 5),6))

Q9:Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

Q10: Let x = np.array([1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]). Create subarray of x by remove the first row and the first column 

##โจทย์พิเศษจ้าาาาาาาาาาาาาาาาาาาาาาาาาาาาา

Special_1 : 

1.1 จงสร้าง Array ขนาด 2*4 ที่มีค่าเป็น 0 ทั้งหมด

1.2 จงสร้าง Array 2 มิติ ที่มีค่าเป็น 1 ทั้งหมด

1.3 จงสร้าง Array 3 มิติที่มีค่าเป็น 0 ทั้งหมด




---


# Copy vs View


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [34]:
# Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
copy = arr.copy()
print(arr)
print(copy)

[1 2 3 4 5]
[1 2 3 4 5]


In [35]:
view = arr.view()
print(view)

[1 2 3 4 5]


In [36]:
arr[2] = 23
print('copy',copy,'\nview', view)

copy [1 2 3 4 5] 
view [ 1  2 23  4  5]




---


# Array Shape

The shape of an array is the number of elements in each dimension.

## Get the Shape of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
# The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

(2, 4)


In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)



---


# Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

## Reshape From 1-D to 2-D

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Array Iterating

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.



In [41]:
# Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


## Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [43]:
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays

In a 3-D array it will go through all the 2-D arrays.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

---

In [ ]:
print(arr)

## <span style="color:red"> Question: </span> Array Iterating

Q1. Let u be an array [0, 1, 2]. From u, create a new array y by using array iterating  <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

Q2. Let x be an array [0, 1, 2]. From x, create a new array y by using array iterating <br/>
[0, 0, 1, 1, 2, 2].

In [44]:
x = np.array([0, 1, 2])

In [45]:
y = np.linspace(0, 5, 6, dtype=int)
print(y)

[0 1 2 3 4 5]


In [ ]:
i = 0
for element in x:
  y[2 * i] = element
  y[2 * i + 1] = element
  i += 1

In [ ]:
print(y)

Q3. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
From x, create a new array y by removing the leading the trailing zeros.

Q4. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. <br>
From x, create two new array y and z which are arrays of unique elements and their counts.


Q5. Let x be an array of vote number [1, 2, 1, 2, 3, 3, 3, 2, 3, 1, 2, 2, 3, 1, 1, 3, 3, 2, 2, 2]. <br>
y be an array of candidate name ["Prawit", "Pitha", "Srettha"] <br>
From x, y counts the score for each candidates.




---


# Joining Array

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [47]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.

In [360]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


## Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.

In [361]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth)

NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [362]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]




---

# Splitting 

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
# import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

In [ ]:
# Split the array in 4 parts:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

## Split Into Arrays

The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:



In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

## Splitting 2-D Arrays

Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

---

## <span style="color:red"> Question: </span> Array Manipulation

Q1. Let x be a ndarray [10, 10, 3] with all elements set to zero. Reshape x so that the size of the second dimension equals 150.

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

Q4. Let x be an arbitrary 2-D array of shape (3, 4). Reshape the dimensions of x to be (4,3).

Q5. Let x be an arbitrary 3-D array of shape (3, 4, 5). Reshape the dimensions of x to be (4,3,5).


Q6. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

Q7. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


Q9. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


Q10. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

Q11. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

Q12. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

Q13. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

Q14. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

Q15. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.



---


# Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

In [ ]:
# Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

In [ ]:
# Find the indexes where the values are odd:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

# Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

In [ ]:
# Sort the array alphabetically:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

In [ ]:
# Sort a boolean array:
arr = np.array([True, False, True])
print(np.sort(arr))

## Sorting a 2-D Array

If you use the sort() method on a 2-D array, both arrays will be sorted:



In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))



---


# Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

## Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [ ]:
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

In [ ]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

## Filter Directly From Array

The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.



In [ ]:
# Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

In [ ]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

---

## <span style="color:red"> Question: </span> 2D-Array and Matrix 

Q1. Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])

In [ ]:
y = np.matrix(X)
y

Q2. Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [ ]:
x = np.array([30])
print(x)
y = x.item()
print(y)

Q3. Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

Q4. Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

Q5. Let $X$ = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 create an array that come from the diagonal of X, that is, [0, 5, 10].

In [ ]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])


Q6. Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere. <br>
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
arr = np.zeros((2,2,4), dtype=int)
print(arr)


In [ ]:
arr[0,0,0] = 1
arr[0,1,1] = 2
arr[1,0,2] = 3
arr[1,1,3] = 4
print(arr)

Q7. Create an array which looks like below. <br>
a = array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

Q8. from array a in Q7. by find $b$ that $a + b = c$ <br>
c = array([[ 0,  0,  0, 1],
       [ 4,  0,  0, 4],
       [ 7,  8,  0, 5],
       [10, 11, 12, 8]])

Q9. from array $c$ in Q8. find $d$ that $c - d = e$ <br>
e = array([[ 1,  2,  3, 1],
       [ 4,  5,  6, 5],
       [ 0,  8,  9, 5],
       [ 0,  0, 12, 1]])

Q10. find matrix transpose of matrix $f$ that create from 2D-array $e$

---